//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace home.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class homeautomationDBEntities : DbContext
    {
        public homeautomationDBEntities()
            : base("name=homeautomationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appliances> appliances { get; set; }
        public virtual DbSet<house> house { get; set; }
        public virtual DbSet<list> list { get; set; }
        public virtual DbSet<settings> settings { get; set; }
        public virtual DbSet<emails> emails { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
