//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace home.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class house
    {
        public house()
        {
            this.appliances = new HashSet<appliances>();
        }
    
        public string Title { get; set; }
        public System.Guid HouseID { get; set; }
    
        public virtual ICollection<appliances> appliances { get; set; }
    }
}
